name: triply
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  hydrated_bloc: ^9.1.5
  flutter_bloc: ^8.1.6
  
  get_it: ^7.7.0
  injectable: ^2.4.2
   
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1

  dio: ^5.4.3+1
  either_dart: ^1.0.0

  connectivity_plus: ^6.0.3
  go_router: ^14.2.0

  skeletonizer: ^1.3.0
  chucker_flutter: ^1.7.2

  equatable: ^2.0.5
  flutter_secure_storage: ^9.2.2
  dartz: ^0.10.1
  path_provider: ^2.1.3
  formz: ^0.7.0

  google_maps_flutter_ios: ^2.7.0
  google_maps_flutter_android: ^2.9.0
  google_maps_flutter_platform_interface: ^2.8.0

  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  firebase_crashlytics: ^4.0.2
  firebase_analytics: ^11.1.0

  google_sign_in: ^6.2.1
  the_apple_sign_in: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2
  build_runner: ^2.4.11
  injectable_generator: ^2.6.1
  flutter_native_splash: ^2.4.0

flutter_native_splash:
  image: "assets/img/triply_icon_logo.jpg"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/img/